import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "@mantine/core/styles.css";
import { MantineProvider, ColorSchemeScript } from "@mantine/core";
import { theme } from "@/lib/theme";
import "@mantine/carousel/styles.css";
import Header from "@/components/layouts/primary/header";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        <main>
          <MantineProvider defaultColorScheme="light" theme={theme}>
            {children}
          </MantineProvider>
        </main>
      </body>
    </html>
  );
}
